// frontend/src/pages/Home.svelte
<script lang="ts">
  import { navigate } from '../router.svelte'
  import { SECTIONS } from '../data/sections'
  import { Card, Gauge, SectionHead, Stamp } from '../components/ui'
</script>

<section class="apps" aria-label="Applicazioni">
  <div class="grid-cards">
    {#each SECTIONS.filter((s) => s.path !== '/') as s (s.path)}
      <Card
        live={s.live}
        glyph={s.glyph}
        title={s.title}
        foot={s.foot}
        href={'#' + s.path}
        onclick={(e) => { e.preventDefault(); navigate(s.path) }}
      />
    {/each}
  </div>
</section>

<section class="app-detail" aria-label="Le applicazioni nel dettaglio">
  <SectionHead
    title="Le applicazioni, nel dettaglio"
    sub="Palamede raccoglie i generatori che giri in casa: un hub, una coda, una wiki per tipo di modello — come funziona, quanto pesa, quanto ci mette, quanto rende, con esempi prodotti dai modelli stessi."
  />
  <div class="app-list">
    {#each SECTIONS.filter((s) => s.path !== '/') as s (s.path)}
      <div class="app-item">
        <span class="glyph">{s.glyph}</span>
        <div class="app-body">
          <h3>
            {s.title}
            <Stamp ok={s.live}>{s.live ? 'attiva' : 'bozza'}</Stamp>
          </h3>
          <p>{s.text}</p>
          <a
            class="app-go"
            href="#{s.path}"
            onclick={(e) => { e.preventDefault(); navigate(s.path) }}
          >
            {s.live ? 'apri la sezione →' : 'vedi la wiki →'}
          </a>
        </div>
      </div>
    {/each}
  </div>
</section>

<section aria-label="Misure" class="bench">
  <SectionHead
    title="Misure sul banco"
    sub="Tempi reali presi su questa macchina, GPU dedicata, warm (cache JIT già scaldata). Il primo colpo a una nuova risoluzione paga qualche secondo in più."
  />
  <Gauge
    cells={[
      { num: '1.8', unit: 's', label: 'Bonsai · 512² · 4 step' },
      { num: '3.3', unit: 's', label: 'Z-Image · 512² · 8 step' },
      { num: '6.4', unit: 's', label: 'Bonsai · 1024² · 4 step' },
      { num: '17.8', unit: 's', label: 'Z-Image · 1024² · 8 step' },
      { num: '6–8.5', unit: 'GB', label: 'VRAM per modello' },
    ]}
  />
</section>

<section class="experimental" aria-label="Sperimentazioni">
  <SectionHead
    title="Sperimentazioni"
    sub="Il riepilogo delle prove in officina: quello che abbiamo tentato e accantonato, e quello che stiamo provando adesso. La cronologia completa con i motivi e i rischi sta nella sezione Experimental."
  />

  <h3 class="exp-group">Provato e accantonato</h3>
  <div class="exp-list">
    <div class="exp-item">
      <span class="exp-state sospeso">sospeso</span>
      <div class="exp-body">
        <h4>Video — Wan 2.1, LTX 2.5, Animatediff</h4>
        <p>
          Tre strade per la generazione video (Wan 2.1 T2V 1.3B con encoder
          UMT5, pipeline LTX 2.5 con VAE e upscaler, Animatediff Lightning
          4-step): pesi in <code>models/_inutilizzati/</code>, mai collegati a
          un backend.
        </p>
      </div>
    </div>
    <div class="exp-item">
      <span class="exp-state sospeso">sospeso</span>
      <div class="exp-body">
        <h4>FLUX.2-klein 9B</h4>
        <p>
          Tentativo di portare la variante 9B oltre al 4B attivo: sd.cpp non
          legge la quantizzazione NVFP4 ModelOpt, quindi dequantizzata in BF16
          (<code>scripts/convert-nvfp4-bf16.py</code>) e provata anche in GGUF
          Q4_0 — accantonata in <code>models/_inutilizzati/klein-9b/</code>.
        </p>
      </div>
    </div>
    <div class="exp-item">
      <span class="exp-state bozza">bozza</span>
      <div class="exp-body">
        <h4>3D — TRELLIS e Hunyuan3D</h4>
        <p>
          Generatori di mesh da testo/immagine via ComfyUI headless: motore e
          modelli mai installati. Vive solo la wiki della sezione.
        </p>
      </div>
    </div>
    <div class="exp-item">
      <span class="exp-state bozza">bozza</span>
      <div class="exp-body">
        <h4>MCP — server per gli agenti</h4>
        <p>
          Esporre l'officina come server MCP stdio (wrapper JSON-RPC su
          <code>/api/image</code>): scritta la wiki, mai il server
          (<code>mcp/server.mjs</code>).
        </p>
      </div>
    </div>
  </div>

  <h3 class="exp-group">In prova adesso</h3>
  <div class="exp-list">
    <div class="exp-item">
      <span class="exp-state prova">in corso</span>
      <div class="exp-body">
        <h4>Model-antivirus</h4>
        <p>
          Scanner d'integrità dei pesi
          (<code>experimental/model-antivirus/</code>): verifica SHA-256 e
          formato all'avvio, audit di affidabilità con l'LLM locale al
          download. Già integrato nel launcher.
        </p>
      </div>
    </div>
    <div class="exp-item">
      <span class="exp-state prova">in corso</span>
      <div class="exp-body">
        <h4>RAG vettoriale — embeddinggemma</h4>
        <p>
          La knowledge base cerca per keyword; <code>embeddinggemma</code> è già
          pronto su Ollama per l'upgrade al RAG vettoriale quando la wiki
          cresce.
        </p>
      </div>
    </div>
  </div>
  <p class="exp-go">
    <a
      class="app-go"
      href="#/experimental"
      onclick={(e) => { e.preventDefault(); navigate('/experimental') }}
    >
      la cronologia completa nella sezione Experimental →
    </a>
  </p>
</section>

// frontend/src/pages/Home.tsx
import { useHashRoute } from '../router'

const SECTIONS = [
  {
    path: '/images', glyph: 'IMG', title: 'Immagini',
    text: 'Due generatori: Bonsai 4B ternary (velocissimo) e Z-Image Turbo Q4 (qualità e testo nell\'immagine).',
    live: true,
    foot: '2 modelli installati · Bonsai + Z-Image',
  },
  {
    path: '/chat', glyph: 'CHT', title: 'Chat',
    text: 'Conversa con Ornith 1.5: 35B-A3B (MoE) e 9B, streaming locale con contesto e KV regolabili.',
    live: true,
    foot: '2 modelli ornith installati',
  },
  {
    path: '/video', glyph: 'VID', title: 'Video',
    text: 'Text-to-video (Wan/LTX) sullo stesso engine che già serve Z-Image.',
    live: false,
    foot: 'engine pronto · pesi mancanti',
  },
  {
    path: '/3d', glyph: '3D', title: '3D',
    text: 'Mesh con texture da descrizione: TRELLIS, Hunyuan3D.',
    live: false,
    foot: 'motore e modelli da installare',
  },
  {
    path: '/rag', glyph: 'RAG', title: 'RAG',
    text: 'Interroga i tuoi documenti con embedding e vettore locale, tutto offline.',
    live: false,
    foot: 'serve un modello embeddings',
  },
  {
    path: '/mcp', glyph: 'MCP', title: 'MCP',
    text: 'Gli strumenti dell\'officina esposti come server MCP per gli agenti.',
    live: false,
    foot: 'primo strumento al rilascio immagini',
  },
]

export function Home() {
  const [, navigate] = useHashRoute()

  return (
    <>
      <section className="apps" aria-label="Applicazioni">
        <div className="grid-cards">
          {SECTIONS.map((s) => (
            <a
              key={s.path}
              className={`card ${s.live ? 'live-card' : ''}`}
              href={'#' + s.path}
              onClick={(e) => { e.preventDefault(); navigate(s.path) }}
            >
              <span className={`state ${s.live ? 'live' : 'bozza'}`}>
                {s.live ? 'attiva' : 'bozza'}
              </span>
              <span className="glyph">{s.glyph}</span>
              <h3>{s.title}</h3>
              <span className="app-foot">{s.foot}</span>
            </a>
          ))}
        </div>
      </section>

      <section className="app-detail" aria-label="Le applicazioni nel dettaglio">
        <h2 className="sec-title">Le applicazioni, nel dettaglio</h2>
        <p className="sec-sub">
          Palamede raccoglie i generatori che giri in casa: un hub, una coda,
          una wiki per tipo di modello — come funziona, quanto pesa, quanto ci
          mette, quanto rende, con esempi prodotti dai modelli stessi.
        </p>
        <div className="app-list">
          {SECTIONS.map((s) => (
            <div className="app-item" key={s.path}>
              <span className="glyph">{s.glyph}</span>
              <div className="app-body">
                <h3>
                  {s.title}
                  <span className={`stamp ${s.live ? 'ok' : ''}`}>
                    {s.live ? 'attiva' : 'bozza'}
                  </span>
                </h3>
                <p>{s.text}</p>
                <a
                  className="app-go"
                  href={'#' + s.path}
                  onClick={(e) => { e.preventDefault(); navigate(s.path) }}
                >
                  {s.live ? 'apri la sezione →' : 'vedi la wiki →'}
                </a>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section aria-label="Misure" className="bench">
        <h2 className="sec-title">Misure sul banco</h2>
        <p className="sec-sub">
          Tempi reali presi su questa macchina, GPU dedicata, warm (cache JIT
          già scaldata). Il primo colpo a una nuova risoluzione paga qualche
          secondo in più.
        </p>
        <div className="gauge">
          <div className="cell">
            <div className="num">1.8<small> s</small></div>
            <div className="lab">Bonsai · 512² · 4 step</div>
          </div>
          <div className="cell">
            <div className="num">3.3<small> s</small></div>
            <div className="lab">Z-Image · 512² · 8 step</div>
          </div>
          <div className="cell">
            <div className="num">6.4<small> s</small></div>
            <div className="lab">Bonsai · 1024² · 4 step</div>
          </div>
          <div className="cell">
            <div className="num">17.8<small> s</small></div>
            <div className="lab">Z-Image · 1024² · 8 step</div>
          </div>
          <div className="cell">
            <div className="num">6–8.5<small> GB</small></div>
            <div className="lab">VRAM per modello</div>
          </div>
        </div>
      </section>
    </>
  )
}
